// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARtoVvuxynNJ4_-yonDVtRgxOxhEJyRX4',
    appId: '1:750867193094:web:2d338a73b73eb185615287',
    messagingSenderId: '750867193094',
    projectId: 'todolist-7f3b3',
    authDomain: 'todolist-7f3b3.firebaseapp.com',
    databaseURL: 'https://todolist-7f3b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todolist-7f3b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8KxGkHFG2GsLZmqa76lGIBDzJxmu3oDE',
    appId: '1:750867193094:android:7c86b18d11faa254615287',
    messagingSenderId: '750867193094',
    projectId: 'todolist-7f3b3',
    databaseURL: 'https://todolist-7f3b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todolist-7f3b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7qgUsfIYjde-K3CVIROc4_ep-EanPHnc',
    appId: '1:750867193094:ios:1bb5bc3a06101d1c615287',
    messagingSenderId: '750867193094',
    projectId: 'todolist-7f3b3',
    databaseURL: 'https://todolist-7f3b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todolist-7f3b3.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7qgUsfIYjde-K3CVIROc4_ep-EanPHnc',
    appId: '1:750867193094:ios:1bb5bc3a06101d1c615287',
    messagingSenderId: '750867193094',
    projectId: 'todolist-7f3b3',
    databaseURL: 'https://todolist-7f3b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todolist-7f3b3.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARtoVvuxynNJ4_-yonDVtRgxOxhEJyRX4',
    appId: '1:750867193094:web:eae271d1508f059b615287',
    messagingSenderId: '750867193094',
    projectId: 'todolist-7f3b3',
    authDomain: 'todolist-7f3b3.firebaseapp.com',
    databaseURL: 'https://todolist-7f3b3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todolist-7f3b3.firebasestorage.app',
  );

}